name: WorldCivMaster
main: com.worldciv.the60th.Main
version: 1.0
depend: [WorldGuard, WorldEdit, NoteBlockAPI]
load: STARTUP
loadbefore: [mcMMO]
commands:
  toggle:
    description:
    usage:
  dungeon:
    description:
    usage:
  dg:
    description:
    usage:
  news:
    description:
    usage:
  party:
    description:
    usage:
  p:
    description:
    usage:
  worldciv:
    description:
    usage:
  wc:
    description:
    usage:
  local:
    description:
    usage:
  l:
    description:
    usage:
  global:
    description:
    usage:
  g:
    description:
    usage:
  nc:
    description:
    usage:
  anc:
    description:
    usage:
  tc:
    description:
    usage:
  ooc:
    description:
    usage:
  mod:
    description:
    usage:
  admin:
    description:
    usage:
  channels:
    description:
    usage:
  ch:
    description:
    usage:
  polls:
    description:
    usage:
  poll:
    description:
    usage:
permissions:
  worldciv.togglevision:
    description:
  worldciv.cmds:
    description:
  worldciv.news:
    description:
  worldciv.dungeonadmin:
    description:
  worldciv.mod:
    description:
  worldciv.admin:
    description:
  worldciv.chatcolor:
    description:
  worldciv.socialspy:
    description:

